name: Docker Image Build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Hub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mediagrifdevteam/cloud-ci
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          tag_names: true
          snapshot: true
      - name: Publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mediagrif/cloud-ci/cloud-ci
          username: ${{ secrets.username }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_names: true
          snapshot: true
